[package]
name = "steel-city-mailers"
version = "0.1.0"
authors = ["hiimtaylorjones <taylorjonessoftware@gmail.com>"]

[dependencies]
hyper = "0.12.6"
hyper-tls = "0.3.0"
dotenv = "0.10.1"
base64="0.9.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
