[package]
name = "steel-city-mailers"
version = "0.1.0"
authors = ["hiimtaylorjones <taylorjonessoftware@gmail.com>"]

[dependencies]
hyper = "0.11.8"
hyper-tls = "0.1.2"
tokio-core = "0.1"
futures = "0.1"
